# Generated by Django 2.0.3 on 2018-05-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='video',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_title',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='Features',
        ),
    ]
