# Generated by Django 2.0.7 on 2018-07-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_channel_playlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
