# Generated by Django 2.0.7 on 2018-09-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_delete_playlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channel',
            new_name='Page',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='name',
            new_name='number',
        ),
    ]
