# Generated by Django 2.0.7 on 2018-09-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20180923_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='code',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
